"""add uuid field user

Revision ID: 8f101abfa0d7
Revises: bb79ef21d5d8
Create Date: 2024-01-09 15:51:16.637601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f101abfa0d7"
down_revision: Union[str, None] = "bb79ef21d5d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("uid", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "uid")
    # ### end Alembic commands ###
