"""remove uniq

Revision ID: a594636e21bd
Revises: f5a9353d3efe
Create Date: 2024-01-17 20:23:29.201899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a594636e21bd'
down_revision: Union[str, None] = 'f5a9353d3efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decks_game_id_fkey', 'decks', type_='foreignkey')
    op.create_foreign_key(None, 'decks', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('games_room_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rounds_name_key', 'rounds', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rounds_name_key', 'rounds', ['name'])
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_room_id_fkey', 'games', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.create_foreign_key('decks_game_id_fkey', 'decks', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
