"""add exp move

Revision ID: f5a9353d3efe
Revises: c4a1e096a205
Create Date: 2024-01-16 17:45:04.217835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a9353d3efe'
down_revision: Union[str, None] = 'c4a1e096a205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('expired_date', sa.DateTime(), nullable=True))
    op.alter_column('moves', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('moves', 'expired_date')
    # ### end Alembic commands ###
