"""update user

Revision ID: 1a8d8cd67ad2
Revises: 8639c73c0e19
Create Date: 2024-01-09 12:12:20.680670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a8d8cd67ad2"
down_revision: Union[str, None] = "8639c73c0e19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("room_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "rooms", ["room_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "room_id")
    # ### end Alembic commands ###
