"""add user uuid

Revision ID: 27b8660a6555
Revises: 1a8d8cd67ad2
Create Date: 2024-01-09 12:37:57.698767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27b8660a6555"
down_revision: Union[str, None] = "1a8d8cd67ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("uid", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "rooms", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="unique")
    op.drop_column("rooms", "uid")
    # ### end Alembic commands ###
